import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import { ThemeProvider } from "next-themes";
import logoX from "../public/images/logo-x.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        <div className="max-w-160 mx-auto">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <header className="-mx-2">
              <NavBar />
            </header>
            <div className="border border-neutral-400 border-t-0 px-2.5 min-h-screen flex flex-col ">
              <main className=" pt-8 grow"> {children}</main>
            </div>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
